# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3360babefa01e6e7866081aa2a5c9d6ef120d2ceec836d987e80a5eba85993e470b3b7df321364a92c445f58f13ef1b8bb4e23bc3630bd25f359d881fee324d

test:
  secret_key_base: 593f1e41f3a4321acb2660ed43cf9bc5401bf936ab54ae5f786231e78f6e4ac421e68618718e6cf5d9feb09320eec4070c3a8301fdf2b5ab612ed53461f70ae7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
